In [1]:
#Q1
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [5]:
#Q2
import numpy as np
l1=[]
l2=[]
for i in range(0,5):
    ls1=int(input())
    l1.append(ls1)
for i in range(0,5):
    ls2=int(input())
    l2.append(ls2)
narr1=np.array(l1)
narr2=np.array(l2)
print(np.concatenate((narr1,narr2),axis=None))
x=np.sort(narr1)
print(x)
y=np.sort(narr2)
print(y)

3
5
1
4
2
10
7
9
6
8
[ 3  5  1  4  2 10  7  9  6  8]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [19]:
#Q3
import numpy as np
arr=np.arange(24).reshape(3,2,4)
print(arr)
print(arr.ndim)
print(arr.size)

#or
ar1=[[[1,2,3],
      [9,8,7]],
     [[4,5,6],
      [3,2,1]]]
print()
print(ar1)
print(np.size(ar1))
print(np.ndim(ar1))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3
24

[[[1, 2, 3], [9, 8, 7]], [[4, 5, 6], [3, 2, 1]]]
12
3


In [25]:
#Q4
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
b=np.expand_dims(a, axis=1)
print(b)
print(b.shape)
c=a[np.newaxis, :]
print(c)
print(c.shape)

[1 2 3 4 5 6]
(6,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[1 2 3 4 5 6]]
(1, 6)


In [34]:
#Q5
import numpy as np
a1=np.arange(9).reshape(3,3)
a2=a1*2
print(a1)
print(a2)
ha1=np.hstack(a1)
ha2=np.hstack(a2)
print(ha1)
print(ha2)
print(np.vstack(a1))
print(np.vstack(a2))
print(np.vstack(ha1))
print(np.vstack(ha2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[0 1 2 3 4 5 6 7 8]
[ 0  2  4  6  8 10 12 14 16]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]]


In [ ]:
#Q6
Using pandas